package main

// DO NOT EDIT, this file is generated by hover at compile-time for the flutter_secure_storage plugin.

import (
	flutter "github.com/go-flutter-desktop/go-flutter"
	flutter_secure_storage "github.com/Roms1383/flutter_secure_storage/macos"
)

func init() {
	// Only the init function can be tweaked by plugin maker.
	options = append(options, flutter.AddPlugin(&flutter_secure_storage.FlutterSecureStoragePlugin{}))
}
